<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('replyCount',function ($builder){
            return $builder->withCount('replies');
        });
    }

    public function path()
    {
        return "/threads/{$this->channel->slug}/{$this->id}";
    }

    public function replies()
    {
        return $this->hasMany(Reply::class);
    }

    public function creator()
    {
        return $this->belongsTo(User::class, "user_id");
    }

    public function addReply($reply)
    {
        $this->replies()->create($reply);
    }

    public function Channel()
    {
        return $this->belongsTo(Channel::class, "channel_id");
    }

    public function scopeFilter($query, $filters){
       return $filters->apply($query);
    }
}
